name: Deploy to Salesforce Dev

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Salesforce CLI
      run: |
        npm install -g @salesforce/cli
        sf version
    
    - name: Install project dependencies
      run: npm install
    
    - name: Authenticate to Salesforce Dev Org
      run: |
        echo "${{ secrets.SALESFORCE_JWT_KEY }}" > server.key
        sf org login jwt \
          --client-id ${{ secrets.SALESFORCE_CLIENT_ID }} \
          --jwt-key-file server.key \
          --username ${{ secrets.SALESFORCE_USERNAME }} \
          --instance-url ${{ secrets.SALESFORCE_INSTANCE_URL }} \
          --set-default-dev-hub \
          --alias DevOrg
    
    - name: Deploy to Salesforce
      run: |
        sf project deploy start \
          --target-org DevOrg \
          --wait 10 \
          --verbose
    
    - name: Import Sample Data (Dev Only)
      if: github.ref == 'refs/heads/develop'
      run: |
        sf data import tree \
          --target-org DevOrg \
          --files scripts/data/sample-yachts.json,scripts/data/sample-expenses.json,scripts/data/sample-crew.json